/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package midterm.project;

import javax.swing.JComboBox;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author Proud To Be Muslims
 */
public class teacherGUI extends javax.swing.JFrame {

    private int tchindex;

    /**
     * Creates new form teacherGUI
     */
    public teacherGUI() {
        initComponents();
        jLabel34.setText("");
        Homepanel.setVisible(true);
        StudentPanel.setVisible(false);
        clospanel.setVisible(false);
        Rubricspanel.setVisible(false);
        assessmentpanel.setVisible(false);
        rubricslevelpanel.setVisible(false);
        evaluationpanel.setVisible(false);
        tchindex = Administrator.getinstace().gtetchrindex();
        jLabel2.setText(Administrator.getinstace().teacherlist.get(tchindex).getname());
        Administrator.getinstace().loadcourseandstudentinteacher(tchindex);
        Administrator.getinstace().registerStudent(jTable1, tchindex);
        Administrator.getinstace().clostable(jTable2, tchindex);
        Administrator.getinstace().clostable(jTable3, tchindex);
        Administrator.getinstace().coursecomboteacher(jComboBox1, tchindex);
        Administrator.getinstace().assessmnettable(jTable4, tchindex);
        Administrator.getinstace().coursecomboteacher(jComboBox3, tchindex);
        Administrator.getinstace().showeeva(jTable5, tchindex);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        MenuTab = new javax.swing.JPanel();
        menustarter = new javax.swing.JLabel();
        profile_Picture = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        MenuPanel = new javax.swing.JPanel();
        hometab = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Homepanel = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        StudentPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        clospanel = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel19 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        Rubricspanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        assessmentpanel = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        assessmentpanel1 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        add = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel34 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jLabel35 = new javax.swing.JLabel();
        rubricslevelpanel = new javax.swing.JPanel();
        evaluationpanel = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        eva = new javax.swing.JPanel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        jLabel38 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        view = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        jLabel46 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(0, 0, 153));

        jButton17.setBackground(new java.awt.Color(0, 0, 153));
        jButton17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cross.png"))); // NOI18N
        jButton17.setBorder(null);
        jButton17.setBorderPainted(false);
        jButton17.setFocusPainted(false);
        jButton17.setFocusable(false);
        jButton17.setRequestFocusEnabled(false);
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });

        jButton18.setBackground(new java.awt.Color(0, 0, 153));
        jButton18.setForeground(new java.awt.Color(255, 255, 255));
        jButton18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-save-close-20.png"))); // NOI18N
        jButton18.setText("Save");
        jButton18.setBorder(null);
        jButton18.setBorderPainted(false);
        jButton18.setFocusPainted(false);
        jButton18.setOpaque(true);
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton17, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
            .addComponent(jButton18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        MenuTab.setBackground(new java.awt.Color(64, 25, 255));
        MenuTab.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menustarter.setBackground(new java.awt.Color(13, 5, 54));
        menustarter.setForeground(new java.awt.Color(255, 255, 255));
        menustarter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-home-24.png"))); // NOI18N
        menustarter.setText("Home");
        menustarter.setOpaque(true);
        menustarter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menustarterMouseClicked(evt);
            }
        });
        MenuTab.add(menustarter, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 172, 212, 43));

        profile_Picture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-user-male-100.png"))); // NOI18N
        MenuTab.add(profile_Picture, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 106));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Samyan Wahla");
        MenuTab.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 126, -1, -1));
        MenuTab.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 157, 217, -1));

        MenuPanel.setBackground(new java.awt.Color(64, 25, 255));
        MenuPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        hometab.setBackground(new java.awt.Color(13, 5, 54));
        hometab.setForeground(new java.awt.Color(255, 255, 255));
        hometab.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-teacher-24.png"))); // NOI18N
        hometab.setText("View Registered  Student");
        hometab.setOpaque(true);
        hometab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hometabMouseClicked(evt);
            }
        });
        MenuPanel.add(hometab, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 211, 43));

        jLabel3.setBackground(new java.awt.Color(13, 5, 54));
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-man-student-24.png"))); // NOI18N
        jLabel3.setText("Manage Course");
        jLabel3.setOpaque(true);
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        MenuPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 45, 211, 42));

        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-duolingo-logo-20.png"))); // NOI18N
        jLabel6.setText("Powered By The-SaQii");
        MenuPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 285, -1, -1));

        jLabel8.setBackground(new java.awt.Color(13, 5, 54));
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-inspection-24.png"))); // NOI18N
        jLabel8.setText("Mange Asssessment");
        jLabel8.setOpaque(true);
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        MenuPanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 211, 46));

        jLabel9.setBackground(new java.awt.Color(13, 5, 54));
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-test-24.png"))); // NOI18N
        jLabel9.setText("Evaluation Against Student");
        jLabel9.setOpaque(true);
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        MenuPanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 211, 46));

        jLabel47.setBackground(new java.awt.Color(0, 0, 51));
        jLabel47.setForeground(new java.awt.Color(255, 255, 255));
        jLabel47.setIcon(new javax.swing.ImageIcon(getClass().getResource("/midterm/project/icons8-report-card-24.png"))); // NOI18N
        jLabel47.setText("Result Download ");
        jLabel47.setOpaque(true);
        jLabel47.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel47MouseClicked(evt);
            }
        });
        MenuPanel.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 210, 40));

        MenuTab.add(MenuPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 217, -1, -1));

        jLabel5.setBackground(new java.awt.Color(13, 5, 54));
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-exit-24.png"))); // NOI18N
        jLabel5.setText("Logout");
        jLabel5.setOpaque(true);
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        MenuTab.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 118, 115, 33));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Logged in Teacher");
        MenuTab.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 86, 105, 26));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Homepanel.setBackground(new java.awt.Color(204, 204, 0));
        Homepanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-woman-teacher-50.png"))); // NOI18N
        Homepanel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, -1, 50));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-man-teacher-50.png"))); // NOI18N
        Homepanel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, -1, -1));

        jLabel12.setBackground(new java.awt.Color(0, 0, 255));
        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Teachers are Blessings!!");
        jLabel12.setOpaque(true);
        Homepanel.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 470, 30));

        jLabel13.setBackground(new java.awt.Color(255, 51, 51));
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("‘I am not a teacher, but an awakener.’ –Robert Fros");
        jLabel13.setOpaque(true);
        Homepanel.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, 290, 30));

        jLabel14.setBackground(new java.awt.Color(255, 51, 51));
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("To know how to suggest is the art of teaching.’ –Henri-Frédéric Amiel");
        jLabel14.setOpaque(true);
        Homepanel.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, 380, 30));

        jLabel15.setBackground(new java.awt.Color(51, 51, 51));
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText(" ‘Teaching is the profession that teaches all the other professions.’ –Unknown");
        jLabel15.setOpaque(true);
        Homepanel.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 340, 450, 30));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-teacher-phone-call-100.png"))); // NOI18N
        Homepanel.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, 120, -1));

        jLabel17.setBackground(new java.awt.Color(51, 51, 51));
        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 102, 0));
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-lantern-50.png"))); // NOI18N
        jLabel17.setText("Thank You Teacher");
        jLabel17.setOpaque(true);
        Homepanel.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 420, 260, 70));

        jPanel1.add(Homepanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -2, 672, 530));

        StudentPanel.setBackground(new java.awt.Color(0, 51, 204));
        StudentPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        StudentPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 670, 440));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-man-student-24.png"))); // NOI18N
        jLabel18.setText("Registered Students");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(230, 230, 230)
                .addComponent(jLabel18)
                .addContainerGap(241, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel18)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        StudentPanel.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 90));

        jPanel1.add(StudentPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 672, 528));

        clospanel.setBackground(new java.awt.Color(102, 102, 102));
        clospanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable2);

        clospanel.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 670, 460));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-inspection-24.png"))); // NOI18N
        jLabel19.setText("All CLOS With Courses");
        clospanel.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, -1, -1));

        jButton1.setBackground(new java.awt.Color(102, 102, 102));
        jButton1.setText("Edit");
        jButton1.setBorderPainted(false);
        jButton1.setFocusable(false);
        jButton1.setRequestFocusEnabled(false);
        clospanel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 40, -1, -1));

        jPanel1.add(clospanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 672, 528));

        Rubricspanel.setBackground(new java.awt.Color(255, 102, 51));
        Rubricspanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable3);

        Rubricspanel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 670, 460));

        jPanel1.add(Rubricspanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 672, 528));

        assessmentpanel.setBackground(new java.awt.Color(102, 102, 255));
        assessmentpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        assessmentpanel.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, -1, -1));

        assessmentpanel1.setBackground(new java.awt.Color(102, 102, 255));
        assessmentpanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        assessmentpanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, -1, -1));

        jPanel4.setBackground(new java.awt.Color(0, 0, 255));

        jButton2.setBackground(new java.awt.Color(0, 0, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-inspection-24.png"))); // NOI18N
        jButton2.setText("Add");
        jButton2.setBorderPainted(false);
        jButton2.setFocusPainted(false);
        jButton2.setRequestFocusEnabled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 0, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-edit-20.png"))); // NOI18N
        jButton3.setText("View,Edit and Del");
        jButton3.setBorderPainted(false);
        jButton3.setFocusPainted(false);
        jButton3.setRequestFocusEnabled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(392, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        assessmentpanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 50));

        add.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setText("Assessment Name");
        add.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, -1, -1));
        add.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 250, -1));

        jLabel7.setText("Weightage");
        add.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, -1, -1));
        add.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 250, -1));

        jLabel22.setText("Marks");
        add.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, -1, -1));
        add.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 250, -1));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel23.setText("Assessment Component");
        add.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, -1, -1));

        jLabel24.setText("Questions");
        add.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, -1, -1));
        add.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 250, -1));

        jLabel25.setText("Marks");
        add.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, -1, -1));

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        add.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 250, -1));

        jLabel26.setText("Rubrics");
        add.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, -1, -1));
        add.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, 250, -1));

        jButton4.setBackground(new java.awt.Color(102, 102, 102));
        jButton4.setText("Clear");
        jButton4.setBorderPainted(false);
        jButton4.setFocusPainted(false);
        jButton4.setFocusable(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        add.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 420, -1, -1));

        jLabel27.setText("1,2,3 Separate With \",\"");
        add.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 240, -1, -1));

        jLabel28.setText("3,5,2 Separate With \",\"");
        add.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 290, -1, -1));

        jLabel29.setText("Arrays,Function,Data Types");
        add.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 330, 160, 20));

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        add.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 370, 250, -1));

        jLabel30.setText("Select Course");
        add.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 370, -1, -1));

        jLabel31.setText("Assessment 1 etc.");
        add.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 50, -1, -1));

        jLabel32.setText("25% etc note right only 25");
        add.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 100, -1, -1));

        jLabel33.setText("15 (this is total all questions sum up)");
        add.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 140, -1, -1));

        jButton6.setBackground(new java.awt.Color(102, 102, 102));
        jButton6.setText("Add");
        jButton6.setBorderPainted(false);
        jButton6.setFocusPainted(false);
        jButton6.setFocusable(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        add.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 420, -1, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane3.setViewportView(jTextArea1);

        add.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 350, 210, 70));

        jLabel34.setText("jLabel34");
        add.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 250, -1));

        assessmentpanel1.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 670, 480));

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(jTable4);

        jLabel35.setBackground(new java.awt.Color(255, 255, 255));
        jLabel35.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-inspection-24.png"))); // NOI18N
        jLabel35.setText("All Assessments Record");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 670, Short.MAX_VALUE)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(227, 227, 227)
                .addComponent(jLabel35)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel35)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        assessmentpanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, -1, 480));

        assessmentpanel.add(assessmentpanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 672, 528));

        jPanel1.add(assessmentpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 672, 528));

        rubricslevelpanel.setBackground(new java.awt.Color(0, 153, 153));
        rubricslevelpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(rubricslevelpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 672, 528));

        evaluationpanel.setBackground(new java.awt.Color(255, 51, 102));
        evaluationpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(0, 0, 255));

        jButton5.setBackground(new java.awt.Color(0, 0, 255));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-test-24.png"))); // NOI18N
        jButton5.setText("View Evaluation");
        jButton5.setBorderPainted(false);
        jButton5.setContentAreaFilled(false);
        jButton5.setFocusPainted(false);
        jButton5.setFocusable(false);
        jButton5.setRequestFocusEnabled(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(0, 0, 255));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-teacher-24.png"))); // NOI18N
        jButton7.setText("Evaluate");
        jButton7.setBorderPainted(false);
        jButton7.setContentAreaFilled(false);
        jButton7.setFocusPainted(false);
        jButton7.setFocusable(false);
        jButton7.setRequestFocusEnabled(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(jButton7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5)
                .addContainerGap(430, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        evaluationpanel.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 40));

        eva.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        eva.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, 170, -1));

        jLabel36.setText("Student");
        eva.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 50, 20));

        jLabel37.setText("Course");
        eva.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, 20));

        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });
        eva.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 160, -1));

        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });
        eva.add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 20, 140, -1));

        jLabel38.setText("Assessment");
        eva.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, -1, 40));
        eva.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 260, -1));

        jLabel39.setText("Inserts Question Name");
        eva.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, 40));

        jLabel40.setText("e.g. 1,2,3 ");
        eva.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 240, -1, 20));

        jLabel41.setText("Respective Marks");
        eva.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, -1, 20));
        eva.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, 260, -1));

        jLabel42.setText("e.g. 4,5,1");
        eva.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 290, -1, -1));

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane6.setViewportView(jTextArea2);

        eva.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 260, -1));

        jLabel43.setText("Question Details ");
        eva.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        jLabel44.setText("Assessment Name");
        eva.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        jLabel45.setText("Out of Total");
        eva.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 290, -1, -1));

        jButton8.setBackground(new java.awt.Color(102, 102, 102));
        jButton8.setText("Evaluate");
        jButton8.setBorderPainted(false);
        jButton8.setDefaultCapable(false);
        jButton8.setFocusable(false);
        jButton8.setRequestFocusEnabled(false);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        eva.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 360, -1, -1));

        evaluationpanel.add(eva, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 680, 490));

        view.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane7.setViewportView(jTable5);

        view.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 680, 410));

        jLabel46.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-man-student-24.png"))); // NOI18N
        jLabel46.setText("All Evaluation Agasints Students");
        view.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, -1));

        evaluationpanel.add(view, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 680, 490));

        jPanel1.add(evaluationpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 672, 528));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(MenuTab, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(MenuTab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menustarterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menustarterMouseClicked
        // TODO add your handling code here:

        Homepanel.setVisible(true);
        StudentPanel.setVisible(false);
        clospanel.setVisible(false);
        Rubricspanel.setVisible(false);
        assessmentpanel.setVisible(false);
        rubricslevelpanel.setVisible(false);
        evaluationpanel.setVisible(false);
//        Homepanel1.setVisible(false);


    }//GEN-LAST:event_menustarterMouseClicked

    private void hometabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hometabMouseClicked
        // TODO add your handling code here:

        Homepanel.setVisible(false);
        StudentPanel.setVisible(true);
        clospanel.setVisible(false);
        Rubricspanel.setVisible(false);
        assessmentpanel.setVisible(false);
        rubricslevelpanel.setVisible(false);
        evaluationpanel.setVisible(false);
        // Homepanel1.setVisible(false);


    }//GEN-LAST:event_hometabMouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        Homepanel.setVisible(false);
        StudentPanel.setVisible(false);
        clospanel.setVisible(true);
        Rubricspanel.setVisible(false);
        assessmentpanel.setVisible(false);
        rubricslevelpanel.setVisible(false);
        evaluationpanel.setVisible(false);
        // Homepanel1.setVisible(false);
        Administrator.getinstace().clostable(jTable2, tchindex);


    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        Homepanel.setVisible(false);
        StudentPanel.setVisible(false);
        clospanel.setVisible(false);
        Rubricspanel.setVisible(false);
        assessmentpanel.setVisible(true);
        rubricslevelpanel.setVisible(false);
        evaluationpanel.setVisible(false);
        //Homepanel1.setVisible(false);
        Administrator.getinstace().assessmnettable(jTable4, tchindex);
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        Homepanel.setVisible(false);
        StudentPanel.setVisible(false);
        clospanel.setVisible(false);
        Rubricspanel.setVisible(false);
        assessmentpanel.setVisible(false);
        rubricslevelpanel.setVisible(false);
        evaluationpanel.setVisible(true);
        //Homepanel1.setVisible(true);
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        Login_Screen obj = new Login_Screen();
        obj.setVisible(true);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        // TODO add your handling code here:
        Administrator.getinstace().saveAssessment();
        Administrator.getinstace().evasave();
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jTextField5.setText("");
        jTextField6.setText("");

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        add.setVisible(true);
        jPanel7.setVisible(false);
        Administrator.getinstace().assessmnettable(jTable4, tchindex);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

        jPanel7.setVisible(true);
        add.setVisible(false);
        Administrator.getinstace().assessmnettable(jTable4, tchindex);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        String name = jTextField1.getText();
        String weightage = jTextField2.getText();
        String marks = jTextField3.getText();
        String questions = jTextField4.getText();
        String qmarks = jTextField5.getText();
        String rubrics = jTextField6.getText();
        String course = jComboBox1.getItemAt(jComboBox1.getSelectedIndex());
        if (Administrator.getinstace().addassessment(name, weightage, marks, questions, qmarks, rubrics, tchindex, course, jLabel34)) {
            add.setVisible(false);
            jPanel7.setVisible(true);
            Administrator.getinstace().assessmnettable(jTable4, tchindex);
        }

    }//GEN-LAST:event_jButton6ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        String course = jComboBox1.getItemAt(jComboBox1.getSelectedIndex());
        String bbb = Administrator.getinstace().ViewRubrics(course, tchindex);
        jTextArea1.setText(bbb);
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        eva.setVisible(true);
        view.setVisible(false);

    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        view.setVisible(true);
        eva.setVisible(false);

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:     
        String course = jComboBox3.getItemAt(jComboBox3.getSelectedIndex());
        Administrator.getinstace().stdcombopertcher(jComboBox2, tchindex, course);
        Administrator.getinstace().assessmentcombo(jComboBox4, tchindex, course);
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
        // TODO add your handling code here:
        String ass = jComboBox4.getItemAt(jComboBox4.getSelectedIndex());
        jLabel44.setText(ass);
        String box = Administrator.getinstace().questionview(ass, tchindex);
        jTextArea2.setText(box);
    }//GEN-LAST:event_jComboBox4ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        String course = jComboBox3.getItemAt(jComboBox3.getSelectedIndex());
        String stdname = jComboBox2.getItemAt(jComboBox2.getSelectedIndex());
        String assname = jComboBox4.getItemAt(jComboBox4.getSelectedIndex());
        String qs = jTextField7.getText();
        String mrks = jTextField8.getText();
        String teacher = Administrator.getinstace().teacherlist.get(tchindex).getname();
        boolean flag = true;
        for (int i = 0; i < Administrator.getinstace().teacherlist.get(tchindex).evalist.size(); i++) {
            if (Administrator.getinstace().teacherlist.get(tchindex).evalist.get(i).getstdname().equals(stdname) && Administrator.getinstace().teacherlist.get(tchindex).evalist.get(i).getassname().equals(assname)) {
                flag = false;
            }
        }
        if (flag == true) {
            if (Administrator.getinstace().eva(tchindex, course, stdname, assname, qs, mrks, teacher)) {
                Administrator.getinstace().showeeva(jTable5, tchindex);
                eva.setVisible(false);
                view.setVisible(true);

            }
        } else {
            JOptionPane.showMessageDialog(null, "Student Already Evaluated in this Assessment");
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jLabel47MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel47MouseClicked
        // TODO add your handling code here:

        JFileChooser chooser = new JFileChooser();

        chooser.setDialogTitle("Choose a destination to save exported file");
        chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        //
        // disable the "All files" option.
        //
        //chooser.setAcceptAllFileFilterUsed(false);

        if (chooser.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {
            Administrator.getinstace().saveData(chooser.getSelectedFile() + ".csv", tchindex);

        } else {
            System.out.println("No Selection ");
        }
    }//GEN-LAST:event_jLabel47MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(teacherGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(teacherGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(teacherGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(teacherGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new teacherGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Homepanel;
    private javax.swing.JPanel MenuPanel;
    private javax.swing.JPanel MenuTab;
    private javax.swing.JPanel Rubricspanel;
    private javax.swing.JPanel StudentPanel;
    private javax.swing.JPanel add;
    private javax.swing.JPanel assessmentpanel;
    private javax.swing.JPanel assessmentpanel1;
    private javax.swing.JPanel clospanel;
    private javax.swing.JPanel eva;
    private javax.swing.JPanel evaluationpanel;
    private javax.swing.JLabel hometab;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTable5;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JLabel menustarter;
    private javax.swing.JLabel profile_Picture;
    private javax.swing.JPanel rubricslevelpanel;
    private javax.swing.JPanel view;
    // End of variables declaration//GEN-END:variables
}
